export default [
  // currency
  {
    path: "/dashboard/currency",
    name: "currency",
    component: () => import("../../../views/currency/index.vue"),
    meta: {
      breadcrumb: "العملات",
      breadcrumbEn: "currency",
      preLabel: "",
      preLink: "",
    },
  },
  {
    path: "/dashboard/currency/add",
    name: "add-currency",
    component: () => import("../../../views/currency/add-currency/index.vue"),
    meta: {
      breadcrumb: "إضافة عملة",
      breadcrumbEn: "add currency",
      preLabel: "العملة",
      preLabelEn: "currency",
      preLink: "/dashboard/currency",
    },
  },
  {
    path: "/dashboard/currency/edit/:id",
    name: "edit-currency",
    component: () => import("../../../views/currency/edit-currency/index.vue"),
    meta: {
      breadcrumb: "تعديل العملة",
      breadcrumbEn: "edit currency",
      preLabel: "العملة",
      preLabelEn: "currency",
      preLink: "/dashboard/currency",
    },
  },
  {
    path: "/dashboard/currency/show/:id",
    name: "show-currency",
    component: () => import("../../../views/currency/view-currency/index.vue"),
    meta: {
      breadcrumb: "تفاصيل العملة",
      breadcrumbEn: "show currency",
      preLabel: "العملة",
      preLabelEn: "currency",
      preLink: "/dashboard/currency",
    },
  },
  // package
  {
    path: "/dashboard/package",
    name: "package",
    component: () => import("../../../views/package/index.vue"),
    meta: {
      breadcrumb: "الباقات",
      breadcrumbEn: "packages",
      preLabel: "",
      preLink: "",
    },
  },
  {
    path: "/dashboard/package/add",
    name: "add-package",
    component: () => import("../../../views/package/add-package/index.vue"),
    meta: {
      breadcrumb: "إضافة باقة جديدة",
      breadcrumbEn: "add package",
      preLabel: "الباقات",
      preLabelEn: "packages",
      preLink: "/dashboard/package",
    },
  },
  {
    path: "/dashboard/package/edit/:id",
    name: "edit-package",
    component: () => import("../../../views/package/edit-package/index.vue"),
    meta: {
      breadcrumb: "تعديل الباقة",
      breadcrumbEn: "edit package",
      preLabel: "الباقات",
      preLabelEn: "packages",
      preLink: "/dashboard/package",
    },
  },
  {
    path: "/dashboard/package/show/:id",
    name: "show-package",
    component: () => import("../../../views/package/view-package/index.vue"),
    meta: {
      breadcrumb: "تفاصيل الباقة",
      breadcrumbEn: "show package",
      preLabel: "الباقات",
      preLabelEn: "packages",
      preLink: "/dashboard/package",
    },
  },
  // school year
  {
    path: "/dashboard/school-year",
    name: "school-year",
    component: () => import("../../../views/shcool-year/index.vue"),
    meta: {
      breadcrumb: "الأعوام الدراسية",
      breadcrumbEn: "school years",
      preLabel: "",
      preLabelEn: "",
      preLink: "",
    },
  },
  {
    path: "/dashboard/school-year/add",
    name: "add-school-year",
    component: () => import("../../../views/shcool-year/add-school-year/index.vue"),
    meta: {
      breadcrumb: "إضافة عام دراسي",
      breadcrumbEn: "add school year",
      preLabel: "العام الدراسي",
      preLabelEn: "school years",
      preLink: "/dashboard/school-year",
    },
  },
  {
    path: "/dashboard/school-year/edit/:id",
    name: "edit-school-year",
    component: () => import("../../../views/shcool-year/edit-school-year/index.vue"),
    meta: {
      breadcrumb: "تعديل العام الدراسي",
      breadcrumbEn: "edit school year",
      preLabel: "العام الدراسي",
      preLabelEn: "school years",
      preLink: "/dashboard/school-year",
    },
  },
  {
    path: "/dashboard/school-year/show/:id",
    name: "show-school-year",
    component: () => import("../../../views/shcool-year/view-school-year/index.vue"),
    meta: {
      breadcrumb: "تفاصيل العام الدراسي",
      breadcrumbEn: "show school year",
      preLabel: "العام الدراسي",
      preLabelEn: "school years",
      preLink: "/dashboard/school-year",
    },
  },
  // subscription
  {
    path: "/dashboard/subscription",
    name: "subscription",
    component: () => import("../../../views/subscription/index.vue"),
    meta: {
      breadcrumb: "الاشتراكات",
      breadcrumbEn: "subscription",
      preLabel: "",
      preLink: "",
    },
  },
  {
    path: "/dashboard/subscription/add",
    name: "add-subscription",
    component: () => import("../../../views/subscription/add-subscription/index.vue"),
    meta: {
      breadcrumb: "تسجيل اشتراك",
      breadcrumbEn: "add subscription",
      preLabel: "الاشتراكات",
      preLabelEn: "subscription",
      preLink: "/dashboard/subscription",
    },
  },
  {
    path: "/dashboard/subscription/edit/:id",
    name: "edit-subscription",
    component: () => import("../../../views/subscription/edit-subscription/index.vue"),
    meta: {
      breadcrumb: "تعديل الاشتراك",
      breadcrumbEn: "edit subscription",
      preLabel: "الاشتراكات",
      preLabelEn: "subscription",
      preLink: "/dashboard/subscription",
    },
  },
  {
    path: "/dashboard/subscription/show/:id",
    name: "show-subscription",
    component: () => import("../../../views/subscription/view-subscription/index.vue"),
    meta: {
      breadcrumb: "تفاصيل الاشتراك",
      breadcrumbEn: "show subscription",
      preLabel: "الاشتراكات",
      preLabelEn: "subscription",
      preLink: "/dashboard/subscription",
    },
  },
  // role
  {
    path: "/dashboard/role",
    name: "role",
    component: () => import("../../../views/role/index.vue"),
    meta: {
      breadcrumb: "الأدوار الوظيفية",
      breadcrumbEn: "Job roles",
      preLabel: "",
      preLink: "",
    },
  },
  {
    path: "/dashboard/role/add",
    name: "add-role",
    component: () => import("../../../views/role/add-role/index.vue"),
    meta: {
      breadcrumb: "إضافة دور وظيفي",
      breadcrumbEn: "add Job role",
      preLabel: "الأدوار الوظيفية",
      preLabelEn: "Job roles",
      preLink: "/dashboard/role",
    },
  },
  {
    path: "/dashboard/role/permission/:id",
    name: "permission",
    component: () => import("../../../views/role/permission/index.vue"),
    meta: {
      breadcrumb: "الصلاحيات",
      breadcrumbEn: "permission",
      preLabel: "صلاحيات النظام",
      preLabelEn: "Job roles",
      preLink: "/dashboard/role",
    },
  },
  {
    path: "/dashboard/role/show/:id",
    name: "show-role",
    component: () => import("../../../views/role/view-role/index.vue"),
    meta: {
      breadcrumb: "تفاصيل صلاحية المستخدم",
      breadcrumbEn: "show role",
      preLabel: "صلاحيات النظام",
      preLabelEn: "Job roles",
      preLink: "/dashboard/role",
    },
  },
  {
    path: "/dashboard/role/edit/:id",
    name: "edit-role",
    component: () => import("../../../views/role/edit-role/index.vue"),
    meta: {
      breadcrumb: "تعديل دور وظيفي",
      breadcrumbEn: "edit role",
      preLabel: "صلاحيات النظام",
      preLabelEn: "Job roles",
      preLink: "/dashboard/role",
    },
  },
  // users
  {
    path: "/dashboard/users",
    name: "users",
    component: () => import("../../../views/users/index.vue"),
    meta: {
      breadcrumb: "مستخدمي إدارة المنظومة",
      breadcrumbEn: "System administration users",
      preLabel: "",
      preLink: "",
    },
  },
  {
    path: "/dashboard/users/add",
    name: "add-users",
    component: () => import("../../../views/users/add-user/index.vue"),
    meta: {
      breadcrumb: "إضافة مستخدم جديد",
      breadcrumbEn: "add users",
      preLabel: "قائمة المستخدمين",
      preLabelEn: "System administration users",
      preLink: "/dashboard/users",
    },
  },
  {
    path: "/dashboard/users/edit/:id",
    name: "edit-users",
    component: () => import("../../../views/users/edit-user/index.vue"),
    meta: {
      breadcrumb: "تعديل بيانات المستخدم",
      breadcrumbEn: "edit users",
      preLabel: "قائمة المستخدمين",
      preLabelEn: "System administration users",
      preLink: "/dashboard/users",
    },
  },
  {
    path: "/dashboard/users/change-password/:id",
    name: "change-password",
    component: () => import("../../../views/users/change-password/index.vue"),
    meta: {
      breadcrumb: "تغيير كلمة المرور",
      breadcrumbEn: "add users",
      preLabel: "قائمة المستخدمين",
      preLabelEn: "System administration users",
      preLink: "/dashboard/users",
    },
  },
  // school users
  {
    path: "/dashboard/schools-users-search",
    name: "schools-users-search",
    component: () => import("../../../views/schools-users-search/index.vue"),
    meta: {
      breadcrumb: "مستخدمين المدارس",
      breadcrumbEn: "School users",
      preLabel: "المدارس",
      preLink: "/dashboard/schools",
    },
  },
  {
    path: "/dashboard/add-user-excel",
    name: "add-user-excel",
    component: () => import("../../../views/schools-users-search/user-excel/index.vue"),
    meta: {
      breadcrumb: "إضافة مستخدمين عن طريق ملف الإكسيل",
      breadcrumbEn: "Add users via Excel file",
      preLabel: "مستخدمين المدارس",
      preLink: "/dashboard/schools-users-search",
    },
  },
  {
    path: "/dashboard/schools-users-search/add",
    name: "add-schools-users-search",
    component: () => import("../../../views/schools-users-search/add-user/index.vue"),
    meta: {
      breadcrumb: "إضافة مستخدم للمدرسة",
      breadcrumbEn: "add school user",
      preLabel: "المدارس",
      preLabelEn: "schools",
      preLink: "/dashboard/schools",
    },
  },
  {
    path: "/dashboard/users/show/:id",
    name: "show-users",
    component: () => import("../../../views/users/view-user/index.vue"),
    meta: {
      breadcrumb: "تفاصيل المستخدم",
      breadcrumbEn: "show user",
      preLabel: "قائمة المستخدمين",
      preLabelEn: "System administration users",
      preLink: "/dashboard/users",
    },
  },
  // question difficulty
  {
    path: "/dashboard/question-difficulty",
    name: "question-difficulty",
    component: () => import("../../../views/question-difficulty/index.vue"),
    meta: {
      breadcrumb: "مستوى السؤال",
      breadcrumbEn: "question difficulty",
      preLabel: "",
      preLink: "",
    },
  },
  {
    path: "/dashboard/question-difficulty/edit/:id",
    name: "edit-question-difficulty",
    component: () =>
      import("../../../views/question-difficulty/edit-question-difficulty/index.vue"),
    meta: {
      breadcrumb: "تعديل  مستوى السؤال",
      breadcrumbEn: "edit question difficulty",
      preLabel: "مستوى السؤال",
      preLabelEn: "question difficulty",
      preLink: "/dashboard/question-difficulty",
    },
  },
  {
    path: "/dashboard/question-difficulty/show/:id",
    name: "show-question-difficulty",
    component: () =>
      import("../../../views/question-difficulty/view-question-difficulty/index.vue"),
    meta: {
      breadcrumb: "تفاصيل  مستوى السؤال",
      breadcrumbEn: "show question difficulty",
      preLabel: "مستوى السؤال",
      preLabelEn: "question difficulty",
      preLink: "/dashboard/question-difficulty",
    },
  },
  // student levels
  {
    path: "/dashboard/student-levels",
    name: "student-levels",
    component: () => import("../../../views/student-levels/index.vue"),
    meta: {
      breadcrumb: "نقاط المستوى",
      breadcrumbEn: "Level points",
      preLabel: "",
      preLink: "",
    },
  },
  // rewarding-actions
  {
    path: "/dashboard/rewarding-actions",
    name: "rewarding-actions",
    component: () => import("../../../views/rewarding-actions/index.vue"),
    meta: {
      breadcrumb: "جوائز التفاعل",
      breadcrumbEn: "rewarding actions",
      preLabel: "",
      preLink: "",
    },
  },
  {
    path: "/dashboard/rewarding-actions/:id",
    name: "rewarding-actions-edit",
    component: () => import("../../../views/rewarding-actions/edit/index.vue"),
    meta: {
      breadcrumb: "تعديل جائزة تفاعل",
      breadcrumbEn: "edit rewarding actions",
      preLabel: "جوائز التفاعل",
      preLabelEn: "rewarding actions",
      preLink: "/dashboard/rewarding-actions",
    },
  },
  {
    path: "/dashboard/rewarding-actions/show/:id",
    name: "show-rewarding-actions",
    component: () => import("../../../views/rewarding-actions/view-rewarding-actions/index.vue"),
    meta: {
      breadcrumb: "تفاصيل جائزة تفاعل",
      breadcrumbEn: "show rewarding actions",
      preLabel: "جوائز التفاعل",
      preLabelEn: "rewarding actions",
      preLink: "/dashboard/rewarding-actions",
    },
  },
]
